### ISSUE TITLE
Fix ObjectID is not JSON Serializable

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#158]
Based on the following trace, I'm assuming that I have incorrect JSON somewhere in the publish endpoint. It looks like there's a mongodb entry that needs to be converted to a `str`. 

It may be the [args](https://github.com/whole-tale/girder_wholetale/blob/master/server/rest/publish.py#L70) structure

itemIds: `["5b2bf538f8615c033d18eeff"]`
taleId: `59a88c18615678000159c35d`
remoteMemberNode: `https://dev.nceas.ucsb.edu/knb/d1/mn/`
authToken: `<insert dev.nceas.ucsb.edu jwt>`
licenseSPDX: `CC-BY-4.0`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5964d7181801c10001061e17') is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 620, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/girder/girder/api/rest.py", line 1190, in GET
    return self.handleRoute('GET', path, params)
  File "/girder/girder/api/rest.py", line 947, in handleRoute
    val = handler(**kwargs)
  File "/girder/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/girder/girder/api/describe.py", line 702, in wrapped
    return fun(*args, **kwargs)
  File "/girder/plugins/wholetale/server/rest/publish.py", line 84, in dataonePublish
    jobModel.scheduleJob(job)
  File "/girder/plugins/jobs/server/models/job.py", line 312, in scheduleJob
    events.trigger('jobs.schedule', info=job)
  File "/girder/girder/events.py", line 310, in trigger
    handler['handler'](e)
  File "/girder/plugins/worker/server/__init__.py", line 134, in schedule
    'apiUrl': getWorkerApiUrl()
  File "/usr/local/lib/python3.5/dist-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: ObjectId('5964d7181801c10001061e17') is not JSON serializable
```

**Comment by Xarthisius** [comment]
Looks like you're passing raw Tale model. It has more than one ObjectId.

**Comment by ThomasThelen** [comment]
This has been fixed
