### ISSUE TITLE
RStudio Build Fails

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#300]
Building an RStudio image will fail with the message `Tale image is invalid`.
I put the full log output on [pastebin](https://pastebin.com/wzvK9Qiu).
I'll note that Jupyter builds fine.

**To Reproduce:**
1. Log into `.stage`
2. Navigate to `Compose`
3. Select `RStudio` as the evironment
4. Add a title and compose the Tale

**Minimal Trace:**
```
[91m/bin/sh: 1: R: not found
,
[0mRemoving intermediate container 49f3bcdcf3bd
,
The command '/bin/sh -c R --quiet -e "install.packages('devtools', repos='https://mran.microsoft.com/snapshot/2018-02-01', method='libcurl')" && R --quiet -e "devtools::install_github('IRkernel/IRkernel', ref='0.8.11')" && R --quiet -e "IRkernel::installspec(prefix='$NB_PYTHON_PREFIX')"' returned a non-zero code: 127The command '/bin/sh -c R --quiet -e "install.packages('devtools', repos='https://mran.microsoft.com/snapshot/2018-02-01', method='libcurl')" && R --quiet -e "devtools::install_github('IRkernel/IRkernel', ref='0.8.11')" && R --quiet -e "IRkernel::installspec(prefix='$NB_PYTHON_PREFIX')"' returned a non-zero code: 127

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/repo2docker/__main__.py", line 350, in main

    r2d.start()

  File "/usr/local/lib/python3.7/site-packages/repo2docker/app.py", line 703, in start

    self.build()

  File "/usr/local/lib/python3.7/site-packages/repo2docker/app.py", line 689, in build

    raise docker.errors.BuildError(l['error'], build_log='')

docker.errors.BuildError: The command '/bin/sh -c R --quiet -e "install.packages('devtools', repos='https://mran.microsoft.com/snapshot/2018-02-01', method='libcurl')" && R --quiet -e "devtools::install_github('IRkernel/IRkernel', ref='0.8.11')" && R --quiet -e "IRkernel::installspec(prefix='$NB_PYTHON_PREFIX')"' returned a non-zero code: 127
ValueError: Error building tale 5cc88090cd7157c3ecbed627
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 391, in build_tale_image
    raise ValueError('Error building tale {}'.format(tale_id))
```

**Comment by Xarthisius** [comment]
We no longer use plain R image, just Rocker in prod/stage. Can this be closed?

**Comment by ThomasThelen** [comment]
Tested on production and things worked properly
