### ISSUE TITLE
Failed to get citation for Globus dataset

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#312]
Found in v0.7rc3

We're not getting the citation for this Globus dataset. From my testing, the  `path_to_root` only has 2 items.  The folder for the item does have the identifier, and the identifier does resolve via datacite.

Test case:
* Go to https://dashboard.stage.wholetale.org
* Create or launch a tale
* Add dataset "Accelerated Discovery of Metallic Glasses through Iteration of Machine Learning and High-Throughput Experiments"
* "No citable data" appears on metadata page with the following error in girder:

```
Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 630, in endpointDecorator
    val = fun(self, path, params)
  File "/girder/girder/api/rest.py", line 1228, in PUT
    return self.handleRoute('PUT', path, params)
  File "/girder/girder/api/rest.py", line 967, in handleRoute
    val = handler(**kwargs)
  File "/girder/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/girder/girder/api/describe.py", line 709, in wrapped
    return fun(*args, **kwargs)
  File "/girder/plugins/wholetale/server/rest/tale.py", line 149, in updateTale
    event = events.trigger('tale.update_citation', eventParams)
  File "/girder/girder/events.py", line 314, in trigger
    handler['handler'](e)
  File "/girder/plugins/wholetale/server/lib/__init__.py", line 109, in update_citation
    top_identifier = provider.getDatasetUID(doc, user)
  File "/girder/plugins/wholetale/server/lib/globus/globus_provider.py", line 110, in getDatasetUID
    return path_to_root[2]['object']['meta']['identifier']
IndexError: list index out of range
Additional info:
  Request URL: PUT https://girder.stage.wholetale.org/api/v1/tale/5cfb7969b6ff80c717d6bad6
  Query string:
```

**Comment by Xarthisius** [comment]
I believe that should be resolved by running `provider_fix.py` on production database.
