### ISSUE TITLE
Update DataONE Python Libraries

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#420]
We use the following Python packages,
```
dataone.common
dataone.libclient
dataone.cli
```

Right now they're under version 3.2.0. 3.5.0, which is [yet to be released](https://github.com/DataONEorg/d1_python/issues/37), will allow us to document file paths of data objects that get published to DataONE.

In anticipation of 3.5.0, I attempted to upgrade to 3.4.7 and get caught on
```
ERROR: dataone-cli 3.4.7 has requirement requests>=2.22.0, but you'll have requests 2.20.1 which is incompatible.
ERROR: dataone-libclient 3.4.7 has requirement requests[security]>=2.22.0, but you'll have requests 2.20.1 which is incompatible.

Traceback (most recent call last):
  File "/girder/girder/utility/plugin_utilities.py", line 115, in loadPlugins
    root, appconf, apiRoot = loadPlugin(plugin, root, appconf, apiRoot)
  File "/girder/girder/utility/plugin_utilities.py", line 239, in loadPlugin
    module = imp.load_module(moduleName, fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/girder/plugins/wholetale/server/__init__.py", line 28, in <module>
    from .rest.account import Account
  File "/girder/plugins/wholetale/server/rest/account.py", line 16, in <module>
    from ..lib import Verificators
  File "/girder/plugins/wholetale/server/lib/__init__.py", line 22, in <module>
    from .globus.globus_provider import GlobusImportProvider
  File "/girder/plugins/wholetale/server/lib/globus/globus_provider.py", line 10, in <module>
    from plugins.wholetale.server.lib.file_map import FileMap
  File "/girder/plugins/wholetale/server/__init__.py", line 28, in <module>
    from .rest.account import Account
  File "/girder/plugins/wholetale/server/rest/account.py", line 16, in <module>
    from ..lib import Verificators
  File "/girder/plugins/wholetale/server/lib/__init__.py", line 24, in <module>
    from .zenodo.provider import ZenodoImportProvider
  File "/girder/plugins/wholetale/server/lib/zenodo/provider.py", line 17, in <module>
    from ...models.tale import Tale
  File "/girder/plugins/wholetale/server/models/tale.py", line 29, in <module>
    from gwvolman.tasks import build_tale_image, BUILD_TALE_IMAGE_STEP_TOTAL
  File "/gwvolman/gwvolman/tasks.py", line 28, in <module>
    from .lib.dataone.publish import DataONEPublishProvider
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 17, in <module>
    from d1_client.mnclient_2_0 import MemberNodeClient_2_0
  File "/usr/local/lib/python3.5/dist-packages/d1_client/mnclient_2_0.py", line 26, in <module>
    import d1_client.baseclient_2_0
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient_2_0.py", line 26, in <module>
    import d1_client.baseclient_1_2
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient_1_2.py", line 26, in <module>
    import d1_client.baseclient_1_1
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient_1_1.py", line 27, in <module>
    import d1_client.baseclient
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 30, in <module>
    import d1_common.utils.ulog
  File "/usr/local/lib/python3.5/dist-packages/d1_common/utils/ulog.py", line 392
    [f"{s.strip():<{max_list[i]}}" for i, s in enumerate(v)]
                                 ^
SyntaxError: invalid syntax
```
during a make dev.

Upping the request version to 2.22.0 seemed to work without any issues (see this line)[https://github.com/whole-tale/girder_wholetale/blob/master/requirements.txt#L5].
It looks like the root of the problem lies over in gwvolman.

**Comment by ThomasThelen** [comment]
Done in #421
